// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package grunt

const (
	Version     = "v1.0.10"
	GitCommit   = "82743ca"          // the commit JUST BEFORE the release
	VersionDate = "2022-04-03 06:24" // UTC
)
