// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package grunt

const (
	Version     = "v1.0.11"
	GitCommit   = "72a008b"          // the commit JUST BEFORE the release
	VersionDate = "2022-06-17 20:31" // UTC
)
