// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package grunt

const (
	Version     = "v1.0.3"
	GitCommit   = "97530c3" // the commit JUST BEFORE the release
	VersionDate = "2021-04-29 10:54" // UTC
)

